OT123-272 endpoint user register
alkemyTech/OT123-SERVER pull request #10
Opened 2022-01-25 19:33 UTC by facundoveliz

2022-01-25 20:46 UTC, dvelezroman requested changes

2022-01-25 20:46 UTC, dvelezroman commented on routes/users.js
> +          result: newUser,
`result: { user: { ...newUser } }`

2022-01-26 01:50 UTC, facundoveliz commented on routes/users.js
> +          result: newUser,
listo!

2022-01-26 18:55 UTC, facundoveliz commented
https://alkemy-labs.atlassian.net/browse/OT123-272

2022-01-27 20:43 UTC, dvelezroman approved these changes
PR ... antes de mergear arreglar conflictos cuando mergeen las ramas madres de este branch

2022-01-27 23:14 UTC, martinmolina1988 approved these changes

2022-01-28 01:09 UTC, merged