Ot123 306/create activities endpoint
alkemyTech/OT123-SERVER pull request #12
Opened 2022-01-26 03:58 UTC by Raymark12

##Description
Implements endpoint for the creation of activities and validates the data using express-validator.

https://alkemy-labs.atlassian.net/browse/OT123-306

2022-01-26 14:15 UTC, dvelezroman requested changes
Se ve bien. aun faltan cambios y mejorar la estructura

2022-01-26 14:15 UTC, dvelezroman commented on controllers/activities.js
> +      result: activities,
corregir como hablamos ayer, iria asi aqui :
`result: { activities: [...activities] }`

2022-01-26 14:15 UTC, dvelezroman commented on controllers/activities.js
> +      msg: 'error to fetch Activities',
`msg: err.message`

2022-01-26 14:15 UTC, dvelezroman commented on controllers/activities.js
> +    })
falta el campo image para crear una nueva actividad ..

2022-01-26 14:15 UTC, dvelezroman commented on models/activities.js
> +    modelName: 'activities',
falta completar el modelo como en #2

2022-01-26 14:15 UTC, dvelezroman commented on routes/activities.js
> +  [
esto sacar como un midleware como lo hablamos ayer... coordinar con los companieros.

2022-01-26 14:15 UTC, dvelezroman commented on routes/index.js
> +router.use('/activities', activitiesRouter)
excelente

2022-01-26 21:07 UTC, dvelezroman commented on routes/activities.js
> +const activitiesController = require('../controllers/activities')
{ createActivity, getActivities } = require('../controllers/activities')

2022-01-26 21:07 UTC, dvelezroman approved these changes
Bien.. solo cambios de formato codigo

2022-01-26 21:07 UTC, dvelezroman commented on routes/activities.js
> +router.get('/', activitiesController.getActivities)
`getActivities`

2022-01-27 14:29 UTC, dvelezroman approved these changes

2022-01-27 18:56 UTC, capomartin approved these changes
OK

2022-01-27 18:57 UTC, merged