Ot123 276/endpoint authenticated user data2
alkemyTech/OT123-SERVER pull request #14
Opened 2022-01-26 08:10 UTC by martinmolina1988

2022-01-26 14:26 UTC, dvelezroman requested changes
Este ticket solo necesita que devuelvas los datos del usuario autenticado...  la ruta debe recibir un token en el header .. y en ese token deben estar los datos o el ID del user que esta autenticado... y con ese ID devuelves la data de la tabla user...

2022-01-26 14:26 UTC, dvelezroman commented on controllers/user.js
> +exports.registerUser = async (req, res) => {
este metodo ya esta hecho en #10

2022-01-26 14:26 UTC, dvelezroman commented
Tampoco hay descripcion en el PR.. no se sabe que se hizo aqui.. es muy importante describir a manera general lo que se hace en un PR para poder tener contexto para la persona que va a revisar el mismo....

2022-01-27 14:24 UTC, dvelezroman requested changes

2022-01-27 14:24 UTC, dvelezroman commented on middlewares/verifyToken.js
> +    req.id = decoded._id
next()

2022-01-27 14:24 UTC, dvelezroman commented on middlewares/verifyToken.js
> +    req.id = decoded._id
revisar porque creo que le mande a cambiar a `.id`

2022-01-27 14:24 UTC, dvelezroman commented on middlewares/verifyToken.js
> +  const bearerToken = req.headers.authorization
el token puede venir mejor con un header : 
`const token = req.headers['x-access-token']`

2022-01-27 14:24 UTC, dvelezroman commented on middlewares/verifyToken.js
> +  const bearerToken = req.headers.authorization
y no necesariamente un bearer

2022-01-27 14:24 UTC, dvelezroman commented on middlewares/verifyToken.js
> +  const bearerToken = req.headers.authorization
y te ahorras la logica esa de sacarle el bearer

`// midleware to check if the user.roleId user is admin
const jwt = require('jsonwebtoken')
const createHttpError = require('http-errors')
const config = require('../config/config').development

const isAdmin = (req, res, next) => {
  const token = req.headers['x-access-token']
  if (!token) {
    const httpError = createHttpError(401, 'No token provided')
    next(httpError)
  }
  jwt.verify(token, config.secret, (err, decoded) => {
    if (err) {
      const httpError = createHttpError(401, 'Failed to authenticate token')
      next(httpError)
    }
    // if (decoded.role === 'Admin') { // cant be 'role'.  it's the table name
    if (decoded.user.userRole === 'Admin') {
      next()
    } else {
      const httpError = createHttpError(401, 'Forbidden access')
      next(httpError)
    }
    return null
  })
  return null
}
module.exports = isAdmin`

2022-01-27 23:52 UTC, martinmolina1988 commented
creacion de middlewares isAdmin y verifyToken, creacion del endpoint userData

2022-01-27 23:52 UTC, merged