OT123-285 - create entry controller and entries route
alkemyTech/OT123-SERVER pull request #17
Opened 2022-01-26 20:27 UTC by capomartin

https://alkemy-labs.atlassian.net/browse/OT123-285

2022-01-26 21:49 UTC, dvelezroman requested changes

2022-01-26 21:49 UTC, dvelezroman commented on app.js
> +const entriesRouter = require('./routes/entries')
va en routes/index.js

2022-01-26 21:49 UTC, dvelezroman commented on routes/entries.js
> +const user = require('../controllers/entry')
sera entry ?

2022-01-27 14:30 UTC, dvelezroman requested changes
Corregir las rutas

2022-01-27 20:33 UTC, capomartin commented on app.js
> +const entriesRouter = require('./routes/entries')
Corregido

2022-01-27 20:34 UTC, capomartin commented on routes/entries.js
> +const user = require('../controllers/entry')
Corregí la ruta y el controlador. Cambie entry por news

2022-01-27 20:48 UTC, dvelezroman approved these changes
Arreglar y megear

2022-01-27 20:48 UTC, dvelezroman commented on controllers/news.js
> +      result: news,
result: { news: [...news] },

2022-01-27 20:48 UTC, dvelezroman commented on controllers/news.js
> +      result: news,
same as above

2022-01-27 20:57 UTC, DarioMJ48 approved these changes
Bien.

2022-01-27 23:02 UTC, merged