OT123-326/endpoint testimonial delete
alkemyTech/OT123-SERVER pull request #23
Opened 2022-01-27 15:50 UTC by facundoveliz

https://alkemy-labs.atlassian.net/browse/OT123-326

2022-01-27 20:39 UTC, dvelezroman requested changes
Bastante bien... solo pequenios cambios

2022-01-27 20:39 UTC, dvelezroman commented on app.js
> +const testimonialsRouter = require('./routes/testimonials')
Sacar y llevar a routes/index.js

2022-01-27 20:39 UTC, dvelezroman commented on app.js
> +app.use('/testimonials', testimonialsRouter)
sacar a routes

2022-01-27 20:39 UTC, dvelezroman commented on controllers/testimonial.js
> +      res.status(500).send({
res.status(500).json({})

2022-01-27 20:39 UTC, dvelezroman commented on controllers/testimonial.js
> +      msg: 'The testimonial was not found.',
error:

2022-01-27 20:39 UTC, dvelezroman commented on controllers/testimonial.js
> +    })
error?

2022-01-28 02:16 UTC, martinmolina1988 approved these changes

2022-01-28 03:58 UTC, facundoveliz commented on controllers/testimonial.js
> +      msg: 'The testimonial was not found.',
que error tendría que colocar en este caso que no hay ningun valor para devolver aparte del mensaje?

2022-01-28 03:58 UTC, facundoveliz commented on controllers/testimonial.js
> +    })
lo mismo de arriba

2022-01-28 19:14 UTC, dvelezroman requested changes

2022-01-28 19:14 UTC, dvelezroman commented on controllers/testimonial.js
> +      res.send(data)
revisar como se envia en los otros controladores ya mergeados

2022-01-28 19:14 UTC, dvelezroman commented on controllers/testimonial.js
> +      msg: 'The testimonial was not found.',
es verdad...

2022-01-28 19:14 UTC, dvelezroman commented on controllers/testimonial.js
> +    })
ok

2022-01-28 22:26 UTC, dvelezroman approved these changes

2022-01-28 22:48 UTC, merged