OT123-353 added user endpoint tests
alkemyTech/OT123-SERVER pull request #44
Opened 2022-01-30 03:24 UTC by facundoveliz

https://alkemy-labs.atlassian.net/browse/OT123-353

2022-01-30 06:50 UTC, DarioMJ48 approved these changes

2022-01-31 13:15 UTC, dvelezroman requested changes
cambiar el response de controller/user.js

2022-01-31 13:15 UTC, dvelezroman commented on controllers/user.js
>        result: token,
`resutl: { user: { ...user }, token }`

2022-01-31 14:09 UTC, facundoveliz commented
fixed requested changes @dvelezroman

2022-01-31 19:25 UTC, dvelezroman approved these changes

2022-01-31 19:25 UTC, dvelezroman commented on controllers/user.js
> +      result: { user: { ...user }, token },
good

2022-01-31 22:35 UTC, merged