Ot123 311/categories migration add model endpoint list
alkemyTech/OT123-SERVER pull request #7
Opened 2022-01-25 18:57 UTC by patriciodfernandez

https://alkemy-labs.atlassian.net/browse/OT123-336
https://alkemy-labs.atlassian.net/browse/OT123-281

Add: Categorie model - Migration
Add: Endpoint List Categories. /Get

2022-01-25 18:59 UTC, megastratofall approved these changes

2022-01-25 19:58 UTC, dvelezroman commented
Actualiza la rama con MAIN ... y corre el comando :
`npm run lint:js:fix` para solucionar los problemas de linteo

2022-01-25 19:58 UTC, dvelezroman requested changes
no borrar el archivo .env.example ... deshacer los cambios y dejarlo como estaba

2022-01-26 21:11 UTC, dvelezroman commented on app.js
> +app.use('/categories', categoriesRouter)
routes/index.js

2022-01-26 21:14 UTC, dvelezroman requested changes

2022-01-26 21:14 UTC, dvelezroman commented on controllers/categorie.js
> +    const categories = await Categorie.findAll({})
`Category`

2022-01-26 21:14 UTC, dvelezroman commented on controllers/categorie.js
> +      msg: 'You are not authorized to view this information',
msg: error.message

2022-01-26 21:14 UTC, dvelezroman commented on models/categorie.js
> +      modelName: "Categorie",
Category

2022-01-26 21:14 UTC, dvelezroman commented on models/categorie.js
> +  Categorie.init(
Category

2022-01-26 21:14 UTC, dvelezroman commented on models/categorie.js
> +  class Categorie extends Model {
Category

2022-01-26 21:14 UTC, dvelezroman commented on routes/categories.js
> +router.get('/', categorie.findAll)
category

2022-01-27 20:25 UTC, dvelezroman requested changes

2022-01-27 20:25 UTC, dvelezroman commented on controllers/category.js
> +      result: [...categories],
`result: categories: [ ...categories ]`

2022-01-27 20:27 UTC, dvelezroman approved these changes
Arreglar esos conflictos y listo

2022-01-27 22:09 UTC, facundoveliz approved these changes

2022-01-27 22:50 UTC, merged