OT-123-257 | Organization endpoint (filter public data by ID)
alkemyTech/OT123-SERVER pull request #9
Opened 2022-01-25 19:31 UTC by DarioMJ48

https://alkemy-labs.atlassian.net/browse/OT123-361

Organization endpoint (filter public data by ID).

2022-01-25 20:53 UTC, dvelezroman commented on .gitignore
> +request.http
?

2022-01-25 20:56 UTC, dvelezroman requested changes

2022-01-25 20:56 UTC, dvelezroman commented on app.js
> +const organizationsRouter = require('./routes/organizations');
mover a la carpeta correspondiente

2022-01-25 20:56 UTC, dvelezroman commented on app.js
> +app.use('/organizations', organizationsRouter);
mover a carpeta routes/index.js

2022-01-25 20:56 UTC, dvelezroman commented on controllers/organizations.controller.js
> +        thisOrganization ? res.json({ name: thisOrganization.name, image: thisOrganization.image, phone: thisOrganization.phone, address: thisOrganization.address, welcomeText: thisOrganization.text}
line too long...

2022-01-25 20:56 UTC, dvelezroman commented on models/organization.js
> +    modelName: 'Organization',
seguir ejemplo de #2

2022-01-25 20:58 UTC, dvelezroman commented on controllers/organizations.controller.js
> +        thisOrganization ? res.json({ name: thisOrganization.name, image: thisOrganization.image, phone: thisOrganization.phone, address: thisOrganization.address, welcomeText: thisOrganization.text}
seguir el patron de la response 
`res.status(statusCode).json({ ok: boolean, result: REsultObject, msg: 'String })`

2022-01-26 14:38 UTC, dvelezroman requested changes
Falta completar el modelo

2022-01-27 01:14 UTC, DarioMJ48 commented
> Falta completar el modelo

¿Qué le falta exactamente? Me basé en el que martinmolina1988 tenía aprobado.

2022-01-27 01:50 UTC, DarioMJ48 commented on models/organization.js
> +    modelName: 'Organization',
¿Está bien ahora?

2022-01-27 20:12 UTC, dvelezroman approved these changes
Buen trabajo

2022-01-27 20:57 UTC, facundoveliz approved these changes

2022-01-27 21:19 UTC, merged

2022-01-27 21:20 UTC, DarioMJ48 commented
OT123-257, 361, 318 & 319. Bien.